Repository PointCloudLibrary/pcl, pull requests merged in 2020-05, with the labels that each got.

#3977 Switch to command line tools in MacOS CI (Broken by 2020 Apr 24 update)
  .ci/azure-pipelines/build-macos.yaml
  test/common/test_io.cpp
Labels: module: ci, platform: macos

#3753 Add pcl::weak_ptr to have a single-switch move from boost:: to std:: weak pointers
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/cloud.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/cloudEditorWidget.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/copyCommand.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/cutCommand.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/deleteCommand.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/denoiseCommand.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/pasteCommand.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/select1DTool.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/select2DTool.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/selectionTransformTool.h
  apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/transformCommand.h
  common/include/pcl/memory.h
  io/include/pcl/io/boost.h
  io/include/pcl/io/openni_camera/openni_driver.h
  io/include/pcl/io/real_sense/real_sense_device_manager.h
Labels: changelog: ABI break, module: io

#3925 Homogenize deprecation with PCL_DEPRECATED
  doc/tutorials/content/sources/registration_api/example2.cpp
  outofcore/include/pcl/outofcore/impl/octree_base.hpp
  outofcore/include/pcl/outofcore/octree_base.h
  outofcore/include/pcl/outofcore/octree_base_node.h
  registration/include/pcl/registration/correspondence_rejection_distance.h
  registration/include/pcl/registration/correspondence_rejection_median_distance.h
  registration/include/pcl/registration/correspondence_rejection_poly.h
  registration/include/pcl/registration/correspondence_rejection_surface_normal.h
  registration/include/pcl/registration/correspondence_rejection_var_trimmed.h
  visualization/src/pcl_visualizer.cpp
Labels: changelog: deprecation, module: outofcore, needs: author reply

#4015 Updating the CI to Ubuntu-latest
  .ci/azure-pipelines/azure-pipelines.yaml
  .ci/azure-pipelines/build-ubuntu.yaml
  .dev/docker/doc/Dockerfile
Labels: module: ci

#4019 [common] Removed empty file
  common/CMakeLists.txt
  common/include/pcl/common/point_operators.h
  examples/features/example_difference_of_normals.cpp
  filters/include/pcl/filters/convolution.h
  filters/include/pcl/filters/impl/convolution_3d.hpp
  filters/include/pcl/filters/pyramid.h
  geometry/include/pcl/geometry/polygon_operations.h
  sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp
  sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration_2d.hpp
  test/common/test_intensity.cpp
  test/common/test_operators.cpp
Labels: changelog: fix, module: common

#3750 Change PCL smart pointers from `boost` to `std`
  common/CMakeLists.txt
  common/include/pcl/memory.h
Labels: changelog: API break, changelog: new feature

#3843 Add pipeline for building PCL's environment docker image
  .ci/azure-pipelines/env.yml
Labels: changelog: new feature, module: ci

#4027 Fix typos in 3d feature tutorial
  doc/tutorials/content/how_features_work.rst
Labels: changelog: fix, module: docs, needs: code review

#4031 Fix typos in tutorials for module `filters`
  doc/tutorials/content/passthrough.rst
  doc/tutorials/content/remove_outliers.rst
  doc/tutorials/content/statistical_outlier.rst
Labels: changelog: fix, module: docs

#4029 [docs] Improve output to match the text in tutorial by adding a newline
  doc/tutorials/content/sources/voxel_grid/voxel_grid.cpp
Labels: changelog: fix, module: docs

#3899 [common] fixes coming from clang-doxy
  common/include/pcl/common/impl/bivariate_polynomial.hpp
  common/include/pcl/common/impl/centroid.hpp
  common/include/pcl/common/impl/copy_point.hpp
  common/include/pcl/common/impl/eigen.hpp
  common/include/pcl/common/impl/gaussian.hpp
  common/include/pcl/common/impl/generate.hpp
  common/include/pcl/common/impl/intensity.hpp
  common/include/pcl/common/impl/intersections.hpp
  common/include/pcl/common/impl/io.hpp
  common/include/pcl/common/impl/norms.hpp
  common/include/pcl/common/impl/pca.hpp
  common/include/pcl/common/impl/piecewise_linear_function.hpp
  common/include/pcl/common/impl/polynomial_calculations.hpp
  common/include/pcl/common/impl/projection_matrix.hpp
  common/include/pcl/common/impl/random.hpp
  common/include/pcl/common/impl/spring.hpp
  common/include/pcl/common/impl/transformation_from_correspondences.hpp
  common/include/pcl/common/impl/transforms.hpp
  common/include/pcl/common/impl/vector_average.hpp
  common/include/pcl/impl/point_types.hpp
  common/include/pcl/point_types.h
  common/include/pcl/range_image/impl/range_image.hpp
  common/include/pcl/range_image/impl/range_image_planar.hpp
  common/include/pcl/range_image/impl/range_image_spherical.hpp
  examples/common/example_check_if_point_is_valid.cpp
  features/include/pcl/features/impl/3dsc.hpp
  features/include/pcl/features/impl/boundary.hpp
  features/include/pcl/features/impl/fpfh.hpp
  features/include/pcl/features/impl/fpfh_omp.hpp
  features/include/pcl/features/impl/intensity_gradient.hpp
  features/include/pcl/features/impl/pfh.hpp
  features/include/pcl/features/impl/principal_curvatures.hpp
  features/include/pcl/features/impl/shot_omp.hpp
  features/include/pcl/features/impl/usc.hpp
  filters/include/pcl/filters/impl/convolution.hpp
  filters/include/pcl/filters/impl/filter.hpp
  filters/include/pcl/filters/impl/local_maximum.hpp
  filters/include/pcl/filters/impl/median_filter.hpp
  filters/include/pcl/filters/impl/model_outlier_removal.hpp
  filters/include/pcl/filters/impl/sampling_surface_normal.hpp
  io/include/pcl/compression/organized_pointcloud_conversion.h
  io/include/pcl/io/impl/point_cloud_image_extractors.hpp
  io/include/pcl/io/impl/vtk_lib_io.hpp
  io/src/robot_eye_grabber.cpp
  keypoints/include/pcl/keypoints/brisk_2d.h
  octree/include/pcl/octree/impl/octree_pointcloud.hpp
  octree/include/pcl/octree/impl/octree_pointcloud_adjacency.hpp
  recognition/src/face_detection/face_detector_data_provider.cpp
  search/include/pcl/search/impl/organized.hpp
  segmentation/include/pcl/segmentation/impl/grabcut_segmentation.hpp
  segmentation/include/pcl/segmentation/impl/region_growing.hpp
  segmentation/include/pcl/segmentation/impl/segment_differences.hpp
  surface/include/pcl/surface/organized_fast_mesh.h
  test/common/test_type_traits.cpp
  test/kdtree/test_kdtree.cpp
  test/search/test_search.cpp
  visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp
Labels: module: common, needs: author reply

#4011 Changes to move tutorials to read the docs
  .dev/docker/doc/Dockerfile
  doc/advanced/CMakeLists.txt
  doc/advanced/content/_templates/layout.html
  doc/advanced/content/conf.py
  doc/requirements.txt
  doc/tutorials/CMakeLists.txt
  doc/tutorials/content/_templates/layout.html
  doc/tutorials/content/conf.py
  doc/tutorials/content/index.rst
Labels: module: tutorials

#4028 Fix minor typos in normal estimation tutorial
  doc/tutorials/content/normal_estimation.rst
Labels: changelog: fix, module: docs

#4038 Fix typos in range image creation tutorial
  doc/tutorials/content/range_image_creation.rst
Labels: module: tutorials

#4037 Fix the problem of failing to make in resampling tutorial
  doc/tutorials/content/resampling.rst
Labels: module: surface

#4049 Remove unused definition of PCL_UNUSED in doxyfile
  doc/doxygen/doxyfile.in
Labels: module: docs, needs: code review

#4052 Fix typo in region growing tutorial
  doc/tutorials/content/region_growing_segmentation.rst
Labels: changelog: fix, module: docs, needs: code review

#4051 [CI] Improve docker ci for other PRs
  .ci/azure-pipelines/env.yml
Labels: changelog: enhancement, module: ci, needs: code review

#4026 [registration] Removing deprecated method `setInputCloud` from public API
  doc/tutorials/content/sources/iccv2011/include/registration.h
  doc/tutorials/content/sources/iccv2011/src/tutorial.cpp
  doc/tutorials/content/sources/iros2011/include/solution/registration.h
  doc/tutorials/content/sources/template_alignment/template_alignment.cpp
  registration/include/pcl/registration/registration.h
Labels: changelog: API break, changelog: fix, module: registration, needs: code review

#3981 [surface] Reduce time taken in `TextureMapping::sortFacesByCamera` from `O(faces*points)` to `O(faces)`
  surface/include/pcl/surface/impl/texture_mapping.hpp
Labels: changelog: enhancement, module: surface, needs: testing

#4056 [Search] Add include for `pcl::isFinite` for compilation on VS2019
  search/include/pcl/search/impl/brute_force.hpp
Labels: changelog: fix, module: search, needs: testing, platform: windows

#4059 Improving packaging status reporting in README.md
  README.md
Labels: needs: code review

#4020 [doc] Add information regarding header include order
  doc/advanced/content/pcl_style_guide.rst
Labels: changelog: enhancement, module: docs, needs: code review

#3931 [common] Add and use a macro to specify EOL for deprecated headers
  common/include/pcl/make_shared.h
  common/include/pcl/pcl_macros.h
  common/include/pcl/point_traits.h
  kdtree/include/pcl/kdtree/flann.h
  keypoints/include/pcl/keypoints/uniform_sampling.h
  tracking/include/pcl/tracking/boost.h
Labels: module: common, needs: more work

#4064 Remove unused variables from exceptions
  common/include/pcl/common/impl/io.hpp
  gpu/people/src/face_detector.cpp
  io/src/hdl_grabber.cpp
  io/src/lzf_image_io.cpp
  io/src/obj_io.cpp
Labels: changelog: fix, module: ci

#4017 [Visualizer] Fixes #4001 and #3452.
  test/visualization/test_visualization.cpp
  visualization/include/pcl/visualization/impl/pcl_visualizer.hpp
Labels: changelog: fix, module: visualization

#4065 [visualization] Deprecate legacy OpenGL backend of VTK
  CMakeLists.txt
  outofcore/tools/outofcore_viewer.cpp
  visualization/include/pcl/visualization/vtk/vtkVertexBufferObject.h
  visualization/include/pcl/visualization/vtk/vtkVertexBufferObjectMapper.h
Labels: changelog: deprecation, module: cmake, module: visualization, needs: testing

#4062 Use pcl::io::raw_read instead of direct call to POSIX function read
  recognition/include/pcl/recognition/impl/linemod/line_rgbd.hpp
Labels: changelog: fix, module: io, needs: testing, platform: windows

#4067 Fix rendering of points.
  visualization/src/point_cloud_handlers.cpp
Labels: changelog: fix, module: visualization, needs: testing

#4058 Removing hardcoded version number from tutorial CI
  .ci/azure-pipelines/tutorials.yaml
Labels: changelog: enhancement, module: ci, needs: code review

#4071 Remove unnecessary includes in examples
  examples/common/example_check_if_point_is_valid.cpp
  examples/common/example_copy_point_cloud.cpp
  examples/common/example_get_max_min_coordinates.cpp
  examples/features/example_difference_of_normals.cpp
  examples/features/example_fast_point_feature_histograms.cpp
  examples/features/example_normal_estimation.cpp
  examples/features/example_point_feature_histograms.cpp
  examples/features/example_principal_curvatures_estimation.cpp
  examples/features/example_rift_estimation.cpp
  examples/features/example_shape_contexts.cpp
  examples/features/example_spin_images.cpp
  examples/filters/example_extract_indices.cpp
  examples/filters/example_remove_nan_from_point_cloud.cpp
  examples/keypoints/example_get_keypoints_indices.cpp
  examples/keypoints/example_sift_keypoint_estimation.cpp
  examples/keypoints/example_sift_normal_keypoint_estimation.cpp
  examples/keypoints/example_sift_z_keypoint_estimation.cpp
  examples/outofcore/example_outofcore.cpp
  examples/outofcore/example_outofcore_with_lod.cpp
  examples/segmentation/example_cpc_segmentation.cpp
  examples/segmentation/example_extract_clusters_normals.cpp
  examples/segmentation/example_lccp_segmentation.cpp
  examples/segmentation/example_region_growing.cpp
  examples/segmentation/example_supervoxels.cpp
  examples/surface/example_nurbs_fitting_closed_curve.cpp
  examples/surface/example_nurbs_fitting_closed_curve3d.cpp
  examples/surface/example_nurbs_fitting_curve2d.cpp
  examples/surface/example_nurbs_fitting_surface.cpp
  examples/surface/example_nurbs_viewer_surface.cpp
  examples/surface/test_nurbs_fitting_surface.cpp
Labels: changelog: fix, module: examples, needs: code review

#4075 Bump version for release
  CHANGES.md
  CMakeLists.txt
  README.md
Labels: needs: code review

#4080 Update `pcl_find_boost` to allow compilation with Boost 1.73 and 1.72
  PCLConfig.cmake.in
  cmake/pcl_find_boost.cmake
Labels: changelog: fix, module: cmake

#4079 Fix error: misplaced deprecation attributes in `vtkVertexBufferObject{,Mapper}`
  visualization/include/pcl/visualization/vtk/vtkVertexBufferObject.h
  visualization/include/pcl/visualization/vtk/vtkVertexBufferObjectMapper.h
Labels: changelog: fix, module: visualization

#3995 Add dockerfiles for testing before release
  .ci/azure-pipelines/release.yaml
  .dev/docker/perception_pcl_ros/Dockerfile
  .dev/docker/perception_pcl_ros/kinetic_rosinstall.yaml
  .dev/docker/perception_pcl_ros/melodic_rosinstall.yaml
  .dev/docker/perception_pcl_ros/package.xml
  .dev/docker/release/Dockerfile
Labels: module: ci, needs: code review

#4081 Fix compile issue in OutofcoreOctreeBase::setLODFilter after switching from boost::shared_ptr to std::shared_ptr
  outofcore/include/pcl/outofcore/impl/octree_base.hpp
Labels: changelog: fix, module: outofcore, needs: code review

#4089 Bump version in CMakeLists.txt post 1.11 release
  CMakeLists.txt
Labels: needs: code review

#4091 Fix error in #4089
  CMakeLists.txt
Labels: needs: code review

#4098 Print that Flann was found.
  cmake/Modules/FindFLANN.cmake
Labels: module: cmake, needs: code review

#4092 [common] Remove use of dynamic allocation in `GaussianKernel::convolve{Rows,Cols}`
  common/src/gaussian.cpp
Labels: changelog: enhancement, module: common, needs: code review

#3992 [github] Add links for discord or SO in Create Issue
  .github/ISSUE_TEMPLATE/config.yml
Labels: needs: code review

#4109 Add pcd file download link, link to source file in normal estimation using integral images tutorial
  doc/tutorials/content/normal_estimation_using_integral_images.rst
Labels: module: docs, needs: code review

#4112 Fix typo in FPFH documentation, $$p_k$$ was used instead of $$p_i$$
  doc/tutorials/content/fpfh_estimation.rst
Labels: changelog: fix, module: docs, needs: code review

#4111 Fix typos in PFH estimation tutorial
  doc/tutorials/content/pfh_estimation.rst
Labels: changelog: fix, module: docs, needs: code review

#4030 remove_outliers tutorial: make the output of -r and -c consistent
  doc/tutorials/content/remove_outliers.rst
  doc/tutorials/content/sources/remove_outliers/remove_outliers.cpp
Labels: module: docs, needs: code review

#4104 [meta] Getting the stale-bot up and running again
  .github/stale.yml
Labels: needs: code review

#3712 Refactor `point_traits.h` to remove warning during doc generation by doxygen
  common/CMakeLists.txt
  common/include/pcl/point_struct_traits.h
  common/include/pcl/register_point_struct.h
  common/include/pcl/type_traits.h
Labels: module: common, needs: code review

#3814 [tracking] format module by clang-format
  .dev/format.sh
  tracking/include/pcl/tracking/approx_nearest_pair_point_cloud_coherence.h
  tracking/include/pcl/tracking/coherence.h
  tracking/include/pcl/tracking/distance_coherence.h
  tracking/include/pcl/tracking/hsv_color_coherence.h
  tracking/include/pcl/tracking/impl/approx_nearest_pair_point_cloud_coherence.hpp
  tracking/include/pcl/tracking/impl/coherence.hpp
  tracking/include/pcl/tracking/impl/distance_coherence.hpp
  tracking/include/pcl/tracking/impl/hsv_color_coherence.hpp
  tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter.hpp
  tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter_omp.hpp
  tracking/include/pcl/tracking/impl/nearest_pair_point_cloud_coherence.hpp
  tracking/include/pcl/tracking/impl/normal_coherence.hpp
  tracking/include/pcl/tracking/impl/particle_filter.hpp
  tracking/include/pcl/tracking/impl/particle_filter_omp.hpp
  tracking/include/pcl/tracking/impl/pyramidal_klt.hpp
  tracking/include/pcl/tracking/impl/tracker.hpp
  tracking/include/pcl/tracking/impl/tracking.hpp
  tracking/include/pcl/tracking/kld_adaptive_particle_filter.h
  tracking/include/pcl/tracking/kld_adaptive_particle_filter_omp.h
  tracking/include/pcl/tracking/nearest_pair_point_cloud_coherence.h
  tracking/include/pcl/tracking/normal_coherence.h
  tracking/include/pcl/tracking/particle_filter.h
  tracking/include/pcl/tracking/particle_filter_omp.h
  tracking/include/pcl/tracking/pyramidal_klt.h
  tracking/include/pcl/tracking/tracker.h
  tracking/include/pcl/tracking/tracking.h
  tracking/src/coherence.cpp
  tracking/src/kld_adaptive_particle_filter.cpp
  tracking/src/particle_filter.cpp
  tracking/src/tracking.cpp
Labels: module: tracking, needs: code review

#4100 Remove WIN32 or replace with _WIN32
  common/include/pcl/pcl_exports.h
  common/src/print.cpp
  gpu/people/src/cuda/nvidia/NCV.hpp
  io/src/lzf.cpp
  io/src/pcd_io.cpp
  outofcore/include/pcl/outofcore/impl/octree_disk_container.hpp
  outofcore/include/pcl/outofcore/octree_disk_container.h
Labels: module: cmake, needs: code review

#4116 [meta] Adding `kind: todo` to exempt list for stale-bot
  .github/stale.yml
Labels: needs: code review, needs: feedback

#4115 Update README.md
  README.md
Labels: needs: code review

#4121 [CI] Try reduce size of binaries on the CI
  .ci/azure-pipelines/build-macos.yaml
  .ci/azure-pipelines/build-ubuntu.yaml
  .ci/azure-pipelines/build-windows.yaml
Labels: module: ci, needs: code review, needs: testing

#4124 Adapt doc Dockerfile to use 20.04 dependencies
  .dev/docker/doc/Dockerfile
Labels: module: ci

#4125 [cmake] Add an option to not compile with OpenMP
  CMakeLists.txt
Labels: module: cmake, needs: code review

#3989 [common] Replace usage of `std::vector<int>` with `Indices`
  common/include/pcl/cloud_iterator.h
  common/include/pcl/common/centroid.h
  common/include/pcl/common/common.h
  common/include/pcl/common/distances.h
  common/include/pcl/common/impl/centroid.hpp
  common/include/pcl/common/impl/common.hpp
  common/include/pcl/common/impl/io.hpp
  common/include/pcl/common/impl/projection_matrix.hpp
  common/include/pcl/common/impl/transforms.hpp
  common/include/pcl/common/io.h
  common/include/pcl/common/poses_from_matches.h
  common/include/pcl/common/projection_matrix.h
  common/include/pcl/common/transforms.h
  common/include/pcl/correspondence.h
  common/include/pcl/impl/cloud_iterator.hpp
  common/include/pcl/impl/pcl_base.hpp
  common/include/pcl/point_cloud.h
  common/include/pcl/types.h
  common/src/correspondence.cpp
  common/src/io.cpp
  common/src/pcl_base.cpp
Labels: changelog: enhancement, module: common, needs: code review

#4025 Clean FLANN includes
  segmentation/include/pcl/segmentation/impl/unary_classifier.hpp
Labels: changelog: fix, module: segmentation, needs: code review

#4006 Remove redundant condition
  cmake/pcl_targets.cmake
Labels: module: cmake, needs: code review

#3980 Update `PointCloud` to conform to requirements of `ReversibleContainer`
  common/include/pcl/point_cloud.h
Labels: changelog: enhancement, module: common, needs: code review

#3934 Add excluded unit tests as test targets
  test/common/CMakeLists.txt
  test/filters/CMakeLists.txt
  test/io/CMakeLists.txt
  test/io/test_octree_compression.cpp
  test/office1.pcd
  test/search/CMakeLists.txt
  test/search/test_auto_search.cpp
  test/search/test_organized.cpp
  test/search/test_organized_index.cpp
  test/surface/CMakeLists.txt
  test/surface/test_poisson.cpp
Labels: changelog: fix, module: test, needs: testing

#4129 [common] Remove one place with useless const on return value
  common/include/pcl/pcl_base.h
Labels: module: common, needs: code review

#4093 Fix NSIS Template for NSIS3
  cmake/Modules/NSIS.template.in
Labels: changelog: fix, module: cmake, needs: code review, platform: windows

#4134 [filters] reduce computations involved in iterating over the pointcloud for `FastBilateral{OMP}`
  filters/include/pcl/filters/impl/fast_bilateral.hpp
  filters/include/pcl/filters/impl/fast_bilateral_omp.hpp
Labels: changelog: enhancement, module: filters, needs: code review

#4130 Fix CUDA incompatibility issues with Eigen and GCC
  .ci/azure-pipelines/env.yml
  .dev/docker/env/Dockerfile
Labels: module: ci, needs: code review, priority: gsoc

#4145 Give more time to go through the stale issues
  .github/stale.yml
Labels: needs: code review

#4147 Fix typos in "Using PCL in your own project" tutorial
  doc/tutorials/content/using_pcl_pcl_config.rst
Labels: module: docs

#4131 Add a job for clang in Ubuntu 18.04
  .ci/azure-pipelines/azure-pipelines.yaml
  .ci/azure-pipelines/build-macos.yaml
  .ci/azure-pipelines/build-ubuntu.yaml
  .ci/azure-pipelines/build-windows.yaml
  .ci/azure-pipelines/build/macos.yaml
  .ci/azure-pipelines/build/ubuntu.yaml
  .ci/azure-pipelines/build/windows.yaml
  registration/include/pcl/registration/impl/ia_fpcs.hpp
Labels: module: ci, needs: code review, priority: gsoc

#4153 Remove redundant checking for existence in STL maps/sets
  visualization/src/cloud_viewer.cpp
Labels: module: visualization

#4101 Add support for CUDA in CI
  .ci/azure-pipelines/azure-pipelines.yaml
  .ci/azure-pipelines/build/ubuntu.yaml
  .dev/docker/env/Dockerfile
Labels: changelog: new feature, module: ci, needs: code review, priority: gsoc
