Repository PointCloudLibrary/pcl, pull requests merged in 2023-11, with the labels that each got.

#5869 CI: update MacOS from 11 to 12
  .ci/azure-pipelines/azure-pipelines.yaml
  README.md
Labels: module: ci

#5872 remove deprecated code for 1.14 release
  gpu/octree/include/pcl/gpu/octree/octree.hpp
  gpu/octree/src/octree.cpp
  segmentation/include/pcl/segmentation/extract_labeled_clusters.h
  segmentation/include/pcl/segmentation/impl/extract_labeled_clusters.hpp
  segmentation/src/extract_clusters.cpp
  surface/include/pcl/surface/ear_clipping.h
Labels: changelog: removal

#5826 Fix freeze in hdl_grabber.cpp
  io/src/hdl_grabber.cpp
Labels: module: io, changelog: fix

#5867 VoxelGridOcclusionEstimation: fix behaviour if sensor origin is inside the voxel grid
  filters/include/pcl/filters/impl/voxel_grid_occlusion_estimation.hpp
  filters/include/pcl/filters/voxel_grid_occlusion_estimation.h
  tools/voxel_grid_occlusion_estimation.cpp
Labels: module: filters, changelog: fix

#5873 [surface] Speed up nurbs surface fitting
  surface/src/on_nurbs/nurbs_solve_eigen.cpp
Labels: changelog: enhancement, module: surface

#5878 Add readthedocs config files
  README.md
  doc/advanced/.readthedocs.yaml
  doc/tutorials/.readthedocs.yaml
Labels: module: docs

#5851 Issue 4718
  benchmarks/CMakeLists.txt
  benchmarks/search/radius_search.cpp
  test/search/test_organized_index.cpp
Labels: module: benchmarks

#5879 Add sphinx-rtd-theme in doc requirements
  doc/requirements.txt
Labels: module: docs

#5886 Semi-Colon Changes
  apps/include/pcl/apps/manual_registration.h
  common/include/pcl/impl/point_types.hpp
  tracking/include/pcl/tracking/impl/tracking.hpp
Labels: changelog: fix

#5801 Update windows docker to .net 4.8 and ltsc2022
  .ci/azure-pipelines/azure-pipelines.yaml
  .ci/azure-pipelines/env.yml
  .dev/docker/windows/Dockerfile
Labels: module: ci, skill: docker

#5892 Use new windows images for CI
  .ci/azure-pipelines/azure-pipelines.yaml
Labels: module: ci, changelog: fix
